version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/profiles?useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: empuser
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - images-data:/data
  database:
    image: "mysql"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: profiles
        MYSQL_USER: empuser
        MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  
volumes:
  db-data:
  images-data: