apiVersion: v1
kind: Service
metadata:
  name: profiles-mysql
  labels:
    app: profiles
spec:
  ports:
    - port: 3306
  selector:
    app: profiles
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: profiles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: profiles-mysql
  labels:
    app: profiles
spec:
  selector:
    matchLabels:
      app: profiles
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: profiles
        tier: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: profiles
        - name: MYSQL_USER
          value: empuser
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim