apiVersion: v1
kind: Service
metadata:
  name: profiles
  labels:
    app: profiles
spec:
  ports:
    - port: 8080
  selector:
    app: profiles
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profiles-pv-claim
  labels:
    app: profiles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: profiles
  labels:
    app: profiles
spec:
  selector:
    matchLabels:
      app: profiles
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: profiles
        tier: frontend
    spec:
      containers:
      - image: rlence86/legacy-to-cloud
        name: profiles
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://profiles-mysql:3306/profiles?useLegacyDatetimeCode=false&serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: empuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: password
        ports:
        - containerPort: 8080
          name: profiles
        volumeMounts:
        - name: profiles-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: profiles-persistent-storage
        persistentVolumeClaim:
          claimName: profiles-pv-claim